# Run tests on every pull request
# Run tests on every commit into `main`
name: Android CI checks

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  checks:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v3
        with:
          lfs: 'true'
          fetch-depth: 0
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Static analysis
        run: ./gradlew lintDebug detekt
      - name: Unit tests
        run: ./gradlew testDebugUnitTest
      - name: Paparazzi
        run: ./gradlew listitem:verifyPaparazziDebug
      - name: Kover report
        run: ./gradlew koverHtmlReportMain koverXmlReportMain
      - name: Kover dump
        run: ./gradlew koverDump -q
      - name: Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./build/reports/kover/reportMain.xml
          flags: unittests
          verbose: true
      - name: Upload reports
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          path: "**/build/reports/**"
          retention-days: 7